export const userConstants = {
	GET_USER_REQUEST: 'USERS_GET_USER_REQUEST',
	GET_USER_SUCCESS: 'USERS_GET_USER_SUCCESS',
	GET_USER_FAILURE: 'USERS_GET_USER_FAILURE',
	UNLOAD_USER: 'USERS_UNLOAD_USER',

	LOGIN_REFRESH_REQUEST: 'USERS_LOGIN_REFRESH_REQUEST',
	LOGIN_REFRESH_SUCCESS: 'USERS_LOGIN_REFRESH_SUCCESS',
	LOGIN_REFRESH_FAILURE: 'USERS_LOGIN_REFRESH_FAILURE',

	LOGIN_REQUEST: 'USERS_LOGIN_REQUEST',
	LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',
	LOGIN_FAILURE: 'USERS_LOGIN_FAILURE',

	REQUEST_NEW_PASSWORD: 'USERS_REQUEST_NEW_PASSWORD',

	REQUEST_UPDATE_USER: 'USERS_REQUEST_UPDATE_USER',
	SUCCESS_UPDATE_USER: 'USERS_SUCCESS_UPDATE_USER',
	FAILURE_UPDATE_USER: 'USERS_FAILURE_UPDATE_USER',

	LOGOUT: 'USERS_LOGOUT',
};